CREATE TABLE `HtmlText`(
	`HtmlTextId` INT AUTO_INCREMENT NOT NULL,
	`ModuleId` INT NOT NULL,
	`Content`  TEXT NOT NULL,
	`CreatedBy` VARCHAR(256) NOT NULL,
	`CreatedOn` DATETIME NOT NULL,
	`ModifiedBy` VARCHAR(256) NOT NULL,
	`ModifiedOn` DATETIME NOT NULL,
  CONSTRAINT `PK_HtmlText` PRIMARY KEY 
  (
	`HtmlTextId` ASC
  )
)
;

ALTER TABLE `HtmlText` ADD CONSTRAINT FOREIGN KEY (`ModuleId`)
REFERENCES `Module` (`ModuleId`)
ON DELETE CASCADE
;
